import type {
  DeckDefinition,
  StartingRole,
  StationFixture,
  WallSegment,
} from '@kybernetes/protocol';

export interface RoomDefinition {
  id: string;
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  tag: string;
}

export const HESPERIA_ROOMS: RoomDefinition[] = [
  { id: 'bridge', name: 'Command Bridge', x: 120, y: 228, width: 200, height: 140, tag: 'DECK-A' },
  {
    id: 'avionics',
    name: 'Avionics & Sensor Matrix',
    x: 320,
    y: 228,
    width: 120,
    height: 140,
    tag: 'DECK-A',
  },
  {
    id: 'life_support',
    name: 'Life Support & Recycler Bay',
    x: 440,
    y: 228,
    width: 160,
    height: 140,
    tag: 'DECK-B',
  },
  {
    id: 'quarters',
    name: 'Crew Berthing Pods',
    x: 600,
    y: 228,
    width: 160,
    height: 140,
    tag: 'DECK-B',
  },
  {
    id: 'mess',
    name: 'Mess Hall & Galley',
    x: 760,
    y: 228,
    width: 160,
    height: 140,
    tag: 'DECK-B',
  },
  {
    id: 'airlock_stbd',
    name: 'Starboard Airlock Vestibule',
    x: 920,
    y: 228,
    width: 100,
    height: 140,
    tag: 'DECK-B',
  },
  {
    id: 'corridor',
    name: 'Central Catwalk Spine',
    x: 120,
    y: 368,
    width: 900,
    height: 64,
    tag: 'CORRIDOR',
  },
  {
    id: 'armory',
    name: 'Tactical Armory & Security',
    x: 120,
    y: 432,
    width: 200,
    height: 140,
    tag: 'DECK-C',
  },
  {
    id: 'airlock_port',
    name: 'Port Airlock Vestibule',
    x: 320,
    y: 432,
    width: 120,
    height: 140,
    tag: 'DECK-C',
  },
  {
    id: 'cargo',
    name: 'Cargo Bay & Ore Hold',
    x: 440,
    y: 432,
    width: 320,
    height: 140,
    tag: 'DECK-C',
  },
  {
    id: 'engineering',
    name: 'Reactor Engineering',
    x: 760,
    y: 432,
    width: 260,
    height: 140,
    tag: 'DECK-D',
  },
];

export const HESPERIA_WALLS: WallSegment[] = [
  // Outer Hull Enclosure (Top Y=228, Bottom Y=572, Left X=120, Right X=1020)
  { id: 'hull_top_l', x1: 120, y1: 228, x2: 950, y2: 228, isOpaque: true, isTraversable: false },
  { id: 'hull_top_r', x1: 990, y1: 228, x2: 1020, y2: 228, isOpaque: true, isTraversable: false },
  {
    id: 'hull_right_upper',
    x1: 1020,
    y1: 228,
    x2: 1020,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'hull_right_mid',
    x1: 1020,
    y1: 368,
    x2: 1020,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'hull_right_lower_1',
    x1: 1020,
    y1: 432,
    x2: 1020,
    y2: 480,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'hull_right_lower_2',
    x1: 1020,
    y1: 520,
    x2: 1020,
    y2: 572,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'hull_bottom_r',
    x1: 1020,
    y1: 572,
    x2: 400,
    y2: 572,
    isOpaque: true,
    isTraversable: false,
  },
  { id: 'hull_bottom_l', x1: 360, y1: 572, x2: 120, y2: 572, isOpaque: true, isTraversable: false },
  { id: 'hull_left', x1: 120, y1: 572, x2: 120, y2: 228, isOpaque: true, isTraversable: false },

  // Upper Deck Partitions (Vertical Y: 228 -> 368)
  {
    id: 'part_bridge_avionics',
    x1: 320,
    y1: 228,
    x2: 320,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'part_avionics_life',
    x1: 440,
    y1: 228,
    x2: 440,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'part_life_quarters',
    x1: 600,
    y1: 228,
    x2: 600,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'part_quarters_mess',
    x1: 760,
    y1: 228,
    x2: 760,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'part_mess_stbd',
    x1: 920,
    y1: 228,
    x2: 920,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },

  // Upper Deck / Spine Horizontal Boundary (Y = 368)
  {
    id: 'spine_top_bridge_1',
    x1: 120,
    y1: 368,
    x2: 200,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_bridge_2',
    x1: 240,
    y1: 368,
    x2: 320,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_avionics_1',
    x1: 320,
    y1: 368,
    x2: 360,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_avionics_2',
    x1: 400,
    y1: 368,
    x2: 440,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_life_1',
    x1: 440,
    y1: 368,
    x2: 500,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_life_2',
    x1: 540,
    y1: 368,
    x2: 600,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_quarters_1',
    x1: 600,
    y1: 368,
    x2: 660,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_quarters_2',
    x1: 700,
    y1: 368,
    x2: 760,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_mess_1',
    x1: 760,
    y1: 368,
    x2: 820,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_mess_2',
    x1: 860,
    y1: 368,
    x2: 920,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_stbd_1',
    x1: 920,
    y1: 368,
    x2: 950,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_top_stbd_2',
    x1: 990,
    y1: 368,
    x2: 1020,
    y2: 368,
    isOpaque: true,
    isTraversable: false,
  },

  // Lower Deck Partitions (Vertical Y: 432 -> 572)
  {
    id: 'part_armory_port',
    x1: 320,
    y1: 432,
    x2: 320,
    y2: 572,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'part_port_cargo',
    x1: 440,
    y1: 432,
    x2: 440,
    y2: 572,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'part_cargo_eng',
    x1: 760,
    y1: 432,
    x2: 760,
    y2: 572,
    isOpaque: true,
    isTraversable: false,
  },

  // Lower Deck / Spine Horizontal Boundary (Y = 432)
  {
    id: 'spine_bot_armory_1',
    x1: 120,
    y1: 432,
    x2: 200,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_bot_armory_2',
    x1: 240,
    y1: 432,
    x2: 320,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_bot_port_1',
    x1: 320,
    y1: 432,
    x2: 360,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_bot_port_2',
    x1: 400,
    y1: 432,
    x2: 440,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_bot_cargo_1',
    x1: 440,
    y1: 432,
    x2: 580,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_bot_cargo_2',
    x1: 620,
    y1: 432,
    x2: 760,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_bot_eng_1',
    x1: 760,
    y1: 432,
    x2: 870,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'spine_bot_eng_2',
    x1: 910,
    y1: 432,
    x2: 1020,
    y2: 432,
    isOpaque: true,
    isTraversable: false,
  },

  // Cargo Bay Mag-Clamp Container Stacks (Solid Freight Blocks)
  {
    id: 'crate_west_top',
    x1: 470,
    y1: 460,
    x2: 520,
    y2: 460,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'crate_west_bot',
    x1: 470,
    y1: 540,
    x2: 520,
    y2: 540,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'crate_west_left',
    x1: 470,
    y1: 460,
    x2: 470,
    y2: 540,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'crate_west_right',
    x1: 520,
    y1: 460,
    x2: 520,
    y2: 540,
    isOpaque: true,
    isTraversable: false,
  },

  {
    id: 'crate_east_top',
    x1: 680,
    y1: 460,
    x2: 730,
    y2: 460,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'crate_east_bot',
    x1: 680,
    y1: 540,
    x2: 730,
    y2: 540,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'crate_east_left',
    x1: 680,
    y1: 460,
    x2: 680,
    y2: 540,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'crate_east_right',
    x1: 730,
    y1: 460,
    x2: 730,
    y2: 540,
    isOpaque: true,
    isTraversable: false,
  },

  // Engineering Reactor Containment Shroud Barriers
  {
    id: 'reactor_shield_north',
    x1: 860,
    y1: 465,
    x2: 920,
    y2: 465,
    isOpaque: true,
    isTraversable: false,
  },
  {
    id: 'reactor_shield_south',
    x1: 860,
    y1: 555,
    x2: 920,
    y2: 555,
    isOpaque: true,
    isTraversable: false,
  },
];

export const HESPERIA_STATIONS: StationFixture[] = [
  {
    id: 'bridge_helm_console',
    deckId: 'deck_a',
    name: 'Command Bridge Helm',
    stationType: 'bridge',
    x: 220,
    y: 290,
    radius: 28,
    prompt: '[E] Access Navigation Helm',
  },
  {
    id: 'avionics_terminal',
    deckId: 'deck_a',
    name: 'Avionics & Sensor Matrix',
    stationType: 'avionics',
    x: 380,
    y: 290,
    radius: 24,
    prompt: '[E] Calibrate Sensor Array',
  },
  {
    id: 'life_support_scrubber',
    deckId: 'deck_b',
    name: 'Bio-Dome Scrubber Console',
    stationType: 'hydroponics',
    x: 520,
    y: 290,
    radius: 28,
    prompt: '[E] Calibrate Scrubbers',
  },
  {
    id: 'berth_pod_alpha',
    deckId: 'deck_b',
    name: 'Crew Bunk Alpha',
    stationType: 'bunk',
    x: 650,
    y: 265,
    radius: 24,
    prompt: '[E] Rest in Bunk Alpha',
  },
  {
    id: 'berth_pod_beta',
    deckId: 'deck_b',
    name: 'Crew Bunk Beta',
    stationType: 'bunk',
    x: 710,
    y: 265,
    radius: 24,
    prompt: '[E] Rest in Bunk Beta',
  },
  {
    id: 'galley_prep_station',
    deckId: 'deck_b',
    name: 'Galley Prep Station',
    stationType: 'mess',
    x: 810,
    y: 290,
    radius: 28,
    prompt: '[E] Prepare Rations',
  },
  {
    id: 'galley_water_dispenser',
    deckId: 'deck_b',
    name: 'Hydration Fountain',
    stationType: 'mess',
    x: 890,
    y: 260,
    radius: 24,
    prompt: '[E] Drink Water',
  },
  {
    id: 'galley_paste_dispenser',
    deckId: 'deck_b',
    name: 'Nutrient Dispenser',
    stationType: 'mess',
    x: 890,
    y: 320,
    radius: 24,
    prompt: '[E] Dispense Nutrient Paste',
  },
  {
    id: 'airlock_stbd_console',
    deckId: 'deck_b',
    name: 'Starboard Airlock Cycling Unit',
    stationType: 'airlock',
    x: 970,
    y: 290,
    radius: 24,
    prompt: '[E] Cycle Starboard Airlock',
  },
  {
    id: 'armory_tactical_locker',
    deckId: 'deck_c',
    name: 'Armory Weapon Locker',
    stationType: 'armory',
    x: 220,
    y: 510,
    radius: 28,
    prompt: '[E] Swap Weapon Loadout',
  },
  {
    id: 'airlock_port_console',
    deckId: 'deck_c',
    name: 'Port Airlock Cycling Unit',
    stationType: 'airlock',
    x: 380,
    y: 510,
    radius: 24,
    prompt: '[E] Cycle Port Airlock',
  },
  {
    id: 'cargo_mag_winch',
    deckId: 'deck_c',
    name: 'Cargo Mag-Winch Terminal',
    stationType: 'cargo',
    x: 600,
    y: 510,
    radius: 28,
    prompt: '[E] Operate Cargo Winch',
  },
  {
    id: 'reactor_primary_console',
    deckId: 'deck_d',
    name: 'Reactor Core Monitor',
    stationType: 'reactor',
    x: 890,
    y: 510,
    radius: 28,
    prompt: '[E] Access Reactor Console',
  },
];

export const HESPERIA_SPAWNS: Record<StartingRole, { x: number; y: number }> = {
  wiper: { x: 850, y: 510 },
  galley_hand: { x: 810, y: 330 },
  security_private: { x: 220, y: 470 },
  hydro_tender: { x: 520, y: 330 },
  stevedore: { x: 560, y: 510 },
};

export const DEFAULT_DECK: DeckDefinition = {
  id: 'css_hesperia_main',
  name: 'CSS Hesperia - Primary Deck',
  width: 1200,
  height: 800,
  walls: HESPERIA_WALLS,
  stations: HESPERIA_STATIONS,
  spawnPoints: HESPERIA_SPAWNS,
};

export function createDefaultDeck(): DeckDefinition {
  return { ...DEFAULT_DECK };
}

export interface LightDefinition {
  id: string;
  name: string;
  x: number;
  y: number;
  radius: number;
  intensity: number;
  color: [number, number, number];
  room?: string;
  flickerSpeed?: number;
  flickerAmount?: number;
}

export const HESPERIA_LIGHTS: LightDefinition[] = [
  // Central Catwalk Spine Bulkhead Lamps (spaced along y=400)
  {
    id: 'light_corr_fwd',
    name: 'Forward Spine Catwalk Bulkhead Lamp',
    x: 280,
    y: 400,
    radius: 180,
    intensity: 1.15,
    color: [1.0, 0.85, 0.6],
    room: 'corridor',
    flickerSpeed: 3.5,
    flickerAmount: 0.04,
  },
  {
    id: 'light_corr_mid',
    name: 'Midship Spine Fluorescent Strip',
    x: 600,
    y: 400,
    radius: 190,
    intensity: 1.0,
    color: [0.75, 0.9, 1.0],
    room: 'corridor',
    flickerSpeed: 4.2,
    flickerAmount: 0.03,
  },
  {
    id: 'light_corr_aft',
    name: 'Aft Engineering Catwalk Lamp',
    x: 890,
    y: 400,
    radius: 180,
    intensity: 1.15,
    color: [1.0, 0.82, 0.55],
    room: 'corridor',
    flickerSpeed: 2.8,
    flickerAmount: 0.04,
  },

  // Upper Deck Room Fixtures (Y = 295)
  {
    id: 'light_bridge',
    name: 'Command Bridge Helm Array',
    x: 220,
    y: 295,
    radius: 180,
    intensity: 1.0,
    color: [0.35, 0.85, 1.0],
    room: 'bridge',
  },
  {
    id: 'light_avionics',
    name: 'Avionics Matrix Server Rack Glow',
    x: 380,
    y: 295,
    radius: 150,
    intensity: 0.95,
    color: [0.2, 0.7, 1.0],
    room: 'avionics',
    flickerSpeed: 6.0,
    flickerAmount: 0.05,
  },
  {
    id: 'light_life_support',
    name: 'Life Support Algae Vat Luminaire',
    x: 520,
    y: 295,
    radius: 160,
    intensity: 1.0,
    color: [0.2, 0.95, 0.45],
    room: 'life_support',
  },
  {
    id: 'light_quarters',
    name: 'Crew Berthing Ambient Array',
    x: 680,
    y: 295,
    radius: 160,
    intensity: 0.9,
    color: [1.0, 0.9, 0.75],
    room: 'quarters',
  },
  {
    id: 'light_mess',
    name: 'Mess Hall Galley Luminaire',
    x: 840,
    y: 295,
    radius: 160,
    intensity: 1.0,
    color: [1.0, 0.98, 0.92],
    room: 'mess',
  },
  {
    id: 'light_airlock_stbd',
    name: 'Starboard Airlock Hazard Strobe',
    x: 970,
    y: 295,
    radius: 140,
    intensity: 0.95,
    color: [1.0, 0.75, 0.2],
    room: 'airlock_stbd',
  },

  // Lower Deck Room Fixtures (Y = 505)
  {
    id: 'light_armory',
    name: 'Armory Security Alert Lamp',
    x: 220,
    y: 505,
    radius: 180,
    intensity: 0.95,
    color: [1.0, 0.65, 0.35],
    room: 'armory',
  },
  {
    id: 'light_airlock_port',
    name: 'Port Airlock Hazard Strobe',
    x: 380,
    y: 505,
    radius: 140,
    intensity: 0.95,
    color: [1.0, 0.75, 0.2],
    room: 'airlock_port',
  },
  {
    id: 'light_cargo',
    name: 'Cargo Bay Industrial Floodlight',
    x: 600,
    y: 505,
    radius: 200,
    intensity: 0.9,
    color: [0.9, 0.9, 0.82],
    room: 'cargo',
  },
  {
    id: 'light_engineering',
    name: 'Reactor Chamber Core Glow',
    x: 890,
    y: 505,
    radius: 190,
    intensity: 1.05,
    color: [0.25, 0.9, 1.0],
    room: 'engineering',
    flickerSpeed: 2.5,
    flickerAmount: 0.08,
  },
];

export const ROOM_AMBIENTS: Record<string, [number, number, number]> = {
  corridor: [0.06, 0.07, 0.1],
  bridge: [0.22, 0.28, 0.35],
  avionics: [0.18, 0.24, 0.32],
  life_support: [0.2, 0.28, 0.22],
  quarters: [0.26, 0.24, 0.22],
  mess: [0.3, 0.3, 0.28],
  airlock_stbd: [0.15, 0.18, 0.22],
  armory: [0.22, 0.22, 0.26],
  airlock_port: [0.15, 0.18, 0.22],
  cargo: [0.2, 0.2, 0.2],
  engineering: [0.24, 0.2, 0.2],
};
