/**
 * StationHub hull spec: screenshot-faithful harbor крест.
 * North band (Habitat 1-4 / Medizin / Sicherheit-Nord), central E-W
 * corridor plus west Kommando stub and east N-S dock spine, south band
 * (Hydroponik / Frachthalle / Reaktorraum / Sicherheit-Sud), and the east
 * Andockschleuse A airlock tube mating the vertical vessel.
 * Physical boarding only: pawns walk korridor_ost -> andock_a -> ship mouth.
 */

import type { HullSpec } from '../hullCompiler.js';

export const STATION_HUB_FRAME_ID = 'station_hub';

export const StationHubSpec: HullSpec = {
  frameId: STATION_HUB_FRAME_ID,
  rooms: [
    { id: 'habitat', rect: { x: 0, y: 0, w: 320, h: 200 }, volumeM3: 380 },
    { id: 'medizin', rect: { x: 320, y: 0, w: 320, h: 200 }, volumeM3: 380 },
    { id: 'sicherheit_nord', rect: { x: 640, y: 0, w: 280, h: 200 }, volumeM3: 340 },
    { id: 'korridor_mitte', rect: { x: 0, y: 200, w: 920, h: 80 }, volumeM3: 180 },
    { id: 'kommando', rect: { x: 0, y: 280, w: 140, h: 200 }, volumeM3: 170 },
    { id: 'hydroponik', rect: { x: 140, y: 280, w: 160, h: 200 }, volumeM3: 190 },
    { id: 'frachthalle', rect: { x: 300, y: 280, w: 220, h: 200 }, volumeM3: 440 },
    { id: 'reaktorraum', rect: { x: 520, y: 280, w: 200, h: 200 }, volumeM3: 400 },
    { id: 'sicherheit_sued', rect: { x: 720, y: 280, w: 200, h: 200 }, volumeM3: 240 },
    { id: 'korridor_ost', rect: { x: 920, y: 120, w: 100, h: 360 }, volumeM3: 90 },
    { id: 'andock_a', rect: { x: 1020, y: 220, w: 120, h: 80 }, volumeM3: 48 },
  ],
  portals: [
    {
      id: 'habitat_korridor',
      roomA: 'habitat',
      roomB: 'korridor_mitte',
      kind: 'door',
      segment: { x1: 140, y1: 200, x2: 180, y2: 200 },
      areaM2: 2,
    },
    {
      id: 'medizin_korridor',
      roomA: 'medizin',
      roomB: 'korridor_mitte',
      kind: 'door',
      segment: { x1: 460, y1: 200, x2: 500, y2: 200 },
      areaM2: 2,
    },
    {
      id: 'sicherheit_nord_korridor',
      roomA: 'sicherheit_nord',
      roomB: 'korridor_mitte',
      kind: 'door',
      segment: { x1: 740, y1: 200, x2: 780, y2: 200 },
      areaM2: 2,
    },
    {
      id: 'sicherheit_nord_ost',
      roomA: 'sicherheit_nord',
      roomB: 'korridor_ost',
      kind: 'door',
      segment: { x1: 920, y1: 140, x2: 920, y2: 180 },
      areaM2: 2,
    },
    {
      id: 'korridor_mitte_ost',
      roomA: 'korridor_mitte',
      roomB: 'korridor_ost',
      kind: 'open',
      segment: { x1: 920, y1: 220, x2: 920, y2: 280 },
      areaM2: 3,
    },
    {
      id: 'kommando_korridor',
      roomA: 'kommando',
      roomB: 'korridor_mitte',
      kind: 'door',
      segment: { x1: 50, y1: 280, x2: 90, y2: 280 },
      areaM2: 2,
    },
    {
      id: 'kommando_hydroponik',
      roomA: 'kommando',
      roomB: 'hydroponik',
      kind: 'door',
      segment: { x1: 140, y1: 350, x2: 140, y2: 390 },
      areaM2: 2,
    },
    {
      id: 'hydroponik_korridor',
      roomA: 'hydroponik',
      roomB: 'korridor_mitte',
      kind: 'door',
      segment: { x1: 180, y1: 280, x2: 220, y2: 280 },
      areaM2: 2,
    },
    {
      id: 'hydroponik_frachthalle',
      roomA: 'hydroponik',
      roomB: 'frachthalle',
      kind: 'door',
      segment: { x1: 300, y1: 350, x2: 300, y2: 390 },
      areaM2: 2,
    },
    {
      id: 'frachthalle_korridor',
      roomA: 'frachthalle',
      roomB: 'korridor_mitte',
      kind: 'door',
      segment: { x1: 380, y1: 280, x2: 420, y2: 280 },
      areaM2: 2.4,
    },
    {
      id: 'frachthalle_reaktor',
      roomA: 'frachthalle',
      roomB: 'reaktorraum',
      kind: 'door',
      segment: { x1: 520, y1: 350, x2: 520, y2: 390 },
      areaM2: 2.4,
    },
    {
      id: 'reaktor_korridor',
      roomA: 'reaktorraum',
      roomB: 'korridor_mitte',
      kind: 'door',
      segment: { x1: 600, y1: 280, x2: 640, y2: 280 },
      areaM2: 2,
    },
    {
      id: 'reaktor_sued',
      roomA: 'reaktorraum',
      roomB: 'sicherheit_sued',
      kind: 'door',
      segment: { x1: 720, y1: 350, x2: 720, y2: 390 },
      areaM2: 2,
    },
    {
      id: 'sued_korridor',
      roomA: 'sicherheit_sued',
      roomB: 'korridor_mitte',
      kind: 'door',
      segment: { x1: 790, y1: 280, x2: 830, y2: 280 },
      areaM2: 2,
    },
    {
      id: 'sued_ost',
      roomA: 'sicherheit_sued',
      roomB: 'korridor_ost',
      kind: 'door',
      segment: { x1: 920, y1: 340, x2: 920, y2: 380 },
      areaM2: 2,
    },
    {
      id: 'korridor_ost_andock',
      roomA: 'korridor_ost',
      roomB: 'andock_a',
      kind: 'airlock',
      segment: { x1: 1020, y1: 220, x2: 1020, y2: 280 },
      areaM2: 2.4,
    },
    {
      id: 'habitat_window',
      roomA: 'habitat',
      roomB: 'space',
      kind: 'window',
      segment: { x1: 100, y1: 0, x2: 220, y2: 0 },
      areaM2: 0,
      window: true,
    },
    {
      id: 'sued_window',
      roomA: 'sicherheit_sued',
      roomB: 'space',
      kind: 'window',
      segment: { x1: 760, y1: 480, x2: 880, y2: 480 },
      areaM2: 0,
      window: true,
    },
  ],
  spawns: {
    fresh_spawn: { x: 100, y: 260 },
    habitat_spawn: { x: 160, y: 100 },
    medizin_spawn: { x: 480, y: 100 },
    fracht_spawn: { x: 410, y: 380 },
    reaktor_spawn: { x: 620, y: 380 },
    andock_spawn: { x: 1080, y: 260 },
    kommando_spawn: { x: 70, y: 380 },
    sued_spawn: { x: 820, y: 380 },
  },
};
